apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.nameSpaces }}
spec:
  selector:
    app: {{ .Values.metadata.name }}
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: {{ .Values.service.port }}
    protocol: TCP